export const heroesList = [
  {
    name: "Akai",
    image: "Akai.jpeg",
    description: "Dancing bear.",
    attack: 1500,
    level: 2,
  },
  {
    name: "Alucard",
    image: "Alucard.jpg",
    description: "Vampire hunter.",
    attack: 1700,
    level: 3,
  },
  {
    name: "Balmond",
    image: "Balmond.jpg",
    description: "King of the Orcs.",
    attack: 1900,
    level: 4,
  },
  {
    name: "Bane",
    image: "Bane.jpg",
    description: "Sea Lord.",
    attack: 1600,
    level: 2,
  },
  {
    name: "Bruno",
    image: "Bruno.jpg",
    description: "Striker.",
    attack: 1200,
    level: 1,
  },
  {
    name: "Chou",
    image: "Chou.jpg",
    description: "Kiss of the Dragon.",
    attack: 1500,
    level: 2,
  },
  {
    name: "CyberPunk",
    image: "CyberPung_Samurai.jpg",
    description: "Samurai of the future",
    attack: 1500,
    level: 2,
  },
  {
    name: "Estes",
    image: "Estes.jpeg",
    description: "King of the Moon Elves.",
    attack: 300,
    level: 2,
  },
  {
    name: "Eudora",
    image: "Eudora.jpg",
    description: "Storm Mistress",
    attack: 1600,
    level: 3,
  },
  {
    name: "Franco",
    image: "Franco.jpg",
    description: "Valhalla Ruller.",
    attack: 1500,
    level: 2,
  },
  {
    name: "Freya",
    image: "Freya.jpg",
    description: "Valkirye",
    attack: 1900,
    level: 4,
  },
  {
    name: "Gord",
    image: "Gord.jpeg",
    description: "Space traveller.",
    attack: 1900,
    level: 4,
  },
  {
    name: "Harith",
    image: "Harith.jpg",
    description: "Time traveller.",
    attack: 1800,
    level: 3,
  },
  {
    name: "Hayabusa",
    image: "Hayabussa.jpg",
    description: "Shadow ninja.",
    attack: 1700,
    level: 3,
  },
  {
    name: "Johnson",
    image: "Johnson.jpg",
    description: "Cybertrone General.",
    attack: 1800,
    level: 4,
  },
  {
    name: "Karina",
    image: "Karina.jpeg",
    description: "DarkELf",
    attack: 2500,
    level: 6,
  },
  {
    name: "Lancelot",
    image: "Lancelot.jpeg",
    description: "Knight assassin.",
    attack: 2000,
    level: 5,
  },
  {
    name: "Leomord",
    image: "Leomord.jpg",
    description: "Dark Knight.",
    attack: 1900,
    level: 4,
  },
  {
    name: "Lesley",
    image: "Lesley.jpg",
    description: "Sniper Assasin.",
    attack: 1900,
    level: 4,
  },
  {
    name: "Minotaur",
    image: "Minotaur.jpg",
    description: "The king of minotaurs.",
    attack: 1500,
    level: 3,
  },
  {
    name: "Miya",
    image: "Miya.jpg",
    description: "MoonElf Sharpshooter.",
    attack: 1700,
    level: 3,
  },
  {
    name: "Nana",
    image: "Nana.jpg",
    description: "LightElf Healer.",
    attack: 1300,
    level: 2,
  },
  {
    name: "Natalia",
    image: "Natalia.jpg",
    description: "Shadow Assassin.",
    attack: 1600,
    level: 3,
  },
  {
    name: "Odette",
    image: "Odette.jpg",
    description: "Mermaid princess.",
    attack: 1500,
    level: 2,
  },
  {
    name: "Rafaela",
    image: "Rafaela.jpg",
    description: "Life Goddess.",
    attack: 1300,
    level: 2,
  },
  {
    name: "Saber",
    image: "Saber.jpg",
    description: "Katana expert.",
    attack: 1600,
    level: 3,
  },
  {
    name: "Sun",
    image: "Sun.jpg",
    description: "Monkey God.",
    attack: 1700,
    level: 3,
  },
  {
    name: "Vexana",
    image: "Vexana.jpg",
    description: "Death General.",
    attack: 1650,
    level: 3,
  },
  {
    name: "Zhask",
    image: "Zhask.jpeg",
    description: "Alien Conqueror.",
    attack: 1750,
    level: 3,
  },
  {
    name: "Zilong",
    image: "Zilong.jpg",
    description: "Glorious General.",
    attack: 1900,
    level: 4,
  },
];
